name: WebCrawler
env:
  APPLICATION_NAME : "eco-web-crawler"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: Java version
        run: java -version
      - name: Installing maven
        run: sudo apt-get -y install maven
      - name: Maven version
        run: mvn -version
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Run tests
        env:
          url: ${{ secrets.URL }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          GOOGLE_SEARCH_ENGINE_TOKEN: ${{ secrets.GOOGLE_SEARCH_ENGINE_TOKEN }}
          PORT: ${{ secrets.PORT }}
        run: mvn test
